<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ContextBin.Application\ContextBin.Application.csproj" />
    <ProjectReference Include="..\ContextBin.Infrastructure\ContextBin.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpShell" Version="2.7.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
